name: Python Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install maturin
      run: pip install maturin

    - name: Build the package
      run: maturin build --release

    - name: Install the package
      run: pip install target/wheels/*.whl

    - name: Install additional test dependencies
      run: pip install pytest numpy matplotlib tqdm networkx

    - name: Run tests
      run: pytest --maxfail=5 --disable-warnings

